###RAIZZZZZZ
GET http://localhost:5271/

###LISTA
GET http://localhost:5271/api/produto/listar

### BUCAR PRODUTO POR ID
GET http://localhost:5271/api/produto/buscar/2e1c28fb-5613-46bf-8c7f-535227c425a0

###CRIAR
POST http://localhost:5271/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Vassoura",
    "quantidade": 3,
    "preco": 57.75
} 

###ATUALIZAR
PATCH http://localhost:5271/api/produto/alterar/2e1c28fb-5613-46bf-8c7f-535227c425a0
Content-Type: application/json

{
    "nome" : "VassouraA",
    "quantidade": 33,
    "preco": 58.75
} 

###DELETAR
DELETE http://localhost:5271/api/produto/deletar/dd656662-2160-4a40-a3d0-27e93b457384
